/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AlinaChatMessage {
    'author': string;
    'avatarSrc': string;
    'date': string;
    'isFromUser': boolean;
    'text': string;
  }
  interface AlinaCookiesPolicy {
    'banner': string;
    'companyName': string;
    'date': string;
    'websiteUrl': string;
  }
  interface AlinaMessageForm {
    'avatarAlt': string;
    'avatarSrc': string;
  }
  interface AlinaPrivacyPolicy {
    'banner': string;
    'companyName': string;
    'date': string;
    'websiteUrl': string;
  }
  interface AlinaTriloader {}
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLAlinaChatMessageElement extends Components.AlinaChatMessage, HTMLStencilElement {}
  var HTMLAlinaChatMessageElement: {
    prototype: HTMLAlinaChatMessageElement;
    new (): HTMLAlinaChatMessageElement;
  };

  interface HTMLAlinaCookiesPolicyElement extends Components.AlinaCookiesPolicy, HTMLStencilElement {}
  var HTMLAlinaCookiesPolicyElement: {
    prototype: HTMLAlinaCookiesPolicyElement;
    new (): HTMLAlinaCookiesPolicyElement;
  };

  interface HTMLAlinaMessageFormElement extends Components.AlinaMessageForm, HTMLStencilElement {}
  var HTMLAlinaMessageFormElement: {
    prototype: HTMLAlinaMessageFormElement;
    new (): HTMLAlinaMessageFormElement;
  };

  interface HTMLAlinaPrivacyPolicyElement extends Components.AlinaPrivacyPolicy, HTMLStencilElement {}
  var HTMLAlinaPrivacyPolicyElement: {
    prototype: HTMLAlinaPrivacyPolicyElement;
    new (): HTMLAlinaPrivacyPolicyElement;
  };

  interface HTMLAlinaTriloaderElement extends Components.AlinaTriloader, HTMLStencilElement {}
  var HTMLAlinaTriloaderElement: {
    prototype: HTMLAlinaTriloaderElement;
    new (): HTMLAlinaTriloaderElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'alina-chat-message': HTMLAlinaChatMessageElement;
    'alina-cookies-policy': HTMLAlinaCookiesPolicyElement;
    'alina-message-form': HTMLAlinaMessageFormElement;
    'alina-privacy-policy': HTMLAlinaPrivacyPolicyElement;
    'alina-triloader': HTMLAlinaTriloaderElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface AlinaChatMessage extends JSXBase.HTMLAttributes<HTMLAlinaChatMessageElement> {
    'author'?: string;
    'avatarSrc'?: string;
    'date'?: string;
    'isFromUser'?: boolean;
    'text'?: string;
  }
  interface AlinaCookiesPolicy extends JSXBase.HTMLAttributes<HTMLAlinaCookiesPolicyElement> {
    'banner'?: string;
    'companyName'?: string;
    'date'?: string;
    'websiteUrl'?: string;
  }
  interface AlinaMessageForm extends JSXBase.HTMLAttributes<HTMLAlinaMessageFormElement> {
    'avatarAlt'?: string;
    'avatarSrc'?: string;
  }
  interface AlinaPrivacyPolicy extends JSXBase.HTMLAttributes<HTMLAlinaPrivacyPolicyElement> {
    'banner'?: string;
    'companyName'?: string;
    'date'?: string;
    'websiteUrl'?: string;
  }
  interface AlinaTriloader extends JSXBase.HTMLAttributes<HTMLAlinaTriloaderElement> {}
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'alina-chat-message': AlinaChatMessage;
    'alina-cookies-policy': AlinaCookiesPolicy;
    'alina-message-form': AlinaMessageForm;
    'alina-privacy-policy': AlinaPrivacyPolicy;
    'alina-triloader': AlinaTriloader;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


